// Generated by trimming giant list from wooorm/iso-639-3 to only langs with ISO 639-1 codes
const languageTable =
[
  {
    "name": "Afar",
    "type": "living",
    "scope": "individual",
    "iso6393": "aar",
    "iso6392B": "aar",
    "iso6392T": "aar",
    "iso6391": "aa"
  },
  {
    "name": "Abkhazian",
    "type": "living",
    "scope": "individual",
    "iso6393": "abk",
    "iso6392B": "abk",
    "iso6392T": "abk",
    "iso6391": "ab"
  },
  {
    "name": "Afrikaans",
    "type": "living",
    "scope": "individual",
    "iso6393": "afr",
    "iso6392B": "afr",
    "iso6392T": "afr",
    "iso6391": "af"
  },
  {
    "name": "Akan",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "aka",
    "iso6392B": "aka",
    "iso6392T": "aka",
    "iso6391": "ak"
  },
  {
    "name": "Amharic",
    "type": "living",
    "scope": "individual",
    "iso6393": "amh",
    "iso6392B": "amh",
    "iso6392T": "amh",
    "iso6391": "am"
  },
  {
    "name": "Arabic",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "ara",
    "iso6392B": "ara",
    "iso6392T": "ara",
    "iso6391": "ar"
  },
  {
    "name": "Aragonese",
    "type": "living",
    "scope": "individual",
    "iso6393": "arg",
    "iso6392B": "arg",
    "iso6392T": "arg",
    "iso6391": "an"
  },
  {
    "name": "Assamese",
    "type": "living",
    "scope": "individual",
    "iso6393": "asm",
    "iso6392B": "asm",
    "iso6392T": "asm",
    "iso6391": "as"
  },
  {
    "name": "Avaric",
    "type": "living",
    "scope": "individual",
    "iso6393": "ava",
    "iso6392B": "ava",
    "iso6392T": "ava",
    "iso6391": "av"
  },
  {
    "name": "Avestan",
    "type": "ancient",
    "scope": "individual",
    "iso6393": "ave",
    "iso6392B": "ave",
    "iso6392T": "ave",
    "iso6391": "ae"
  },
  {
    "name": "Aymara",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "aym",
    "iso6392B": "aym",
    "iso6392T": "aym",
    "iso6391": "ay"
  },
  {
    "name": "Azerbaijani",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "aze",
    "iso6392B": "aze",
    "iso6392T": "aze",
    "iso6391": "az"
  },
  {
    "name": "Bashkir",
    "type": "living",
    "scope": "individual",
    "iso6393": "bak",
    "iso6392B": "bak",
    "iso6392T": "bak",
    "iso6391": "ba"
  },
  {
    "name": "Bambara",
    "type": "living",
    "scope": "individual",
    "iso6393": "bam",
    "iso6392B": "bam",
    "iso6392T": "bam",
    "iso6391": "bm"
  },
  {
    "name": "Belarusian",
    "type": "living",
    "scope": "individual",
    "iso6393": "bel",
    "iso6392B": "bel",
    "iso6392T": "bel",
    "iso6391": "be"
  },
  {
    "name": "Bengali",
    "type": "living",
    "scope": "individual",
    "iso6393": "ben",
    "iso6392B": "ben",
    "iso6392T": "ben",
    "iso6391": "bn"
  },
  {
    "name": "Bislama",
    "type": "living",
    "scope": "individual",
    "iso6393": "bis",
    "iso6392B": "bis",
    "iso6392T": "bis",
    "iso6391": "bi"
  },
  {
    "name": "Tibetan",
    "type": "living",
    "scope": "individual",
    "iso6393": "bod",
    "iso6392B": "tib",
    "iso6392T": "bod",
    "iso6391": "bo"
  },
  {
    "name": "Bosnian",
    "type": "living",
    "scope": "individual",
    "iso6393": "bos",
    "iso6392B": "bos",
    "iso6392T": "bos",
    "iso6391": "bs"
  },
  {
    "name": "Breton",
    "type": "living",
    "scope": "individual",
    "iso6393": "bre",
    "iso6392B": "bre",
    "iso6392T": "bre",
    "iso6391": "br"
  },
  {
    "name": "Bulgarian",
    "type": "living",
    "scope": "individual",
    "iso6393": "bul",
    "iso6392B": "bul",
    "iso6392T": "bul",
    "iso6391": "bg"
  },
  {
    "name": "Catalan",
    "type": "living",
    "scope": "individual",
    "iso6393": "cat",
    "iso6392B": "cat",
    "iso6392T": "cat",
    "iso6391": "ca"
  },
  {
    "name": "Czech",
    "type": "living",
    "scope": "individual",
    "iso6393": "ces",
    "iso6392B": "cze",
    "iso6392T": "ces",
    "iso6391": "cs"
  },
  {
    "name": "Chamorro",
    "type": "living",
    "scope": "individual",
    "iso6393": "cha",
    "iso6392B": "cha",
    "iso6392T": "cha",
    "iso6391": "ch"
  },
  {
    "name": "Chechen",
    "type": "living",
    "scope": "individual",
    "iso6393": "che",
    "iso6392B": "che",
    "iso6392T": "che",
    "iso6391": "ce"
  },
  {
    "name": "Church Slavic",
    "type": "ancient",
    "scope": "individual",
    "iso6393": "chu",
    "iso6392B": "chu",
    "iso6392T": "chu",
    "iso6391": "cu"
  },
  {
    "name": "Chuvash",
    "type": "living",
    "scope": "individual",
    "iso6393": "chv",
    "iso6392B": "chv",
    "iso6392T": "chv",
    "iso6391": "cv"
  },
  {
    "name": "Cornish",
    "type": "living",
    "scope": "individual",
    "iso6393": "cor",
    "iso6392B": "cor",
    "iso6392T": "cor",
    "iso6391": "kw"
  },
  {
    "name": "Corsican",
    "type": "living",
    "scope": "individual",
    "iso6393": "cos",
    "iso6392B": "cos",
    "iso6392T": "cos",
    "iso6391": "co"
  },
  {
    "name": "Cree",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "cre",
    "iso6392B": "cre",
    "iso6392T": "cre",
    "iso6391": "cr"
  },
  {
    "name": "Welsh",
    "type": "living",
    "scope": "individual",
    "iso6393": "cym",
    "iso6392B": "wel",
    "iso6392T": "cym",
    "iso6391": "cy"
  },
  {
    "name": "Danish",
    "type": "living",
    "scope": "individual",
    "iso6393": "dan",
    "iso6392B": "dan",
    "iso6392T": "dan",
    "iso6391": "da"
  },
  {
    "name": "German",
    "type": "living",
    "scope": "individual",
    "iso6393": "deu",
    "iso6392B": "ger",
    "iso6392T": "deu",
    "iso6391": "de"
  },
  {
    "name": "Dhivehi",
    "type": "living",
    "scope": "individual",
    "iso6393": "div",
    "iso6392B": "div",
    "iso6392T": "div",
    "iso6391": "dv"
  },
  {
    "name": "Dzongkha",
    "type": "living",
    "scope": "individual",
    "iso6393": "dzo",
    "iso6392B": "dzo",
    "iso6392T": "dzo",
    "iso6391": "dz"
  },
  {
    "name": "Modern Greek (1453-)",
    "type": "living",
    "scope": "individual",
    "iso6393": "ell",
    "iso6392B": "gre",
    "iso6392T": "ell",
    "iso6391": "el"
  },
  {
    "name": "English",
    "type": "living",
    "scope": "individual",
    "iso6393": "eng",
    "iso6392B": "eng",
    "iso6392T": "eng",
    "iso6391": "en"
  },
  {
    "name": "Esperanto",
    "type": "constructed",
    "scope": "individual",
    "iso6393": "epo",
    "iso6392B": "epo",
    "iso6392T": "epo",
    "iso6391": "eo"
  },
  {
    "name": "Estonian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "est",
    "iso6392B": "est",
    "iso6392T": "est",
    "iso6391": "et"
  },
  {
    "name": "Basque",
    "type": "living",
    "scope": "individual",
    "iso6393": "eus",
    "iso6392B": "baq",
    "iso6392T": "eus",
    "iso6391": "eu"
  },
  {
    "name": "Ewe",
    "type": "living",
    "scope": "individual",
    "iso6393": "ewe",
    "iso6392B": "ewe",
    "iso6392T": "ewe",
    "iso6391": "ee"
  },
  {
    "name": "Faroese",
    "type": "living",
    "scope": "individual",
    "iso6393": "fao",
    "iso6392B": "fao",
    "iso6392T": "fao",
    "iso6391": "fo"
  },
  {
    "name": "Persian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "fas",
    "iso6392B": "per",
    "iso6392T": "fas",
    "iso6391": "fa"
  },
  {
    "name": "Fijian",
    "type": "living",
    "scope": "individual",
    "iso6393": "fij",
    "iso6392B": "fij",
    "iso6392T": "fij",
    "iso6391": "fj"
  },
  {
    "name": "Finnish",
    "type": "living",
    "scope": "individual",
    "iso6393": "fin",
    "iso6392B": "fin",
    "iso6392T": "fin",
    "iso6391": "fi"
  },
  {
    "name": "French",
    "type": "living",
    "scope": "individual",
    "iso6393": "fra",
    "iso6392B": "fre",
    "iso6392T": "fra",
    "iso6391": "fr"
  },
  {
    "name": "Western Frisian",
    "type": "living",
    "scope": "individual",
    "iso6393": "fry",
    "iso6392B": "fry",
    "iso6392T": "fry",
    "iso6391": "fy"
  },
  {
    "name": "Fulah",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "ful",
    "iso6392B": "ful",
    "iso6392T": "ful",
    "iso6391": "ff"
  },
  {
    "name": "Scottish Gaelic",
    "type": "living",
    "scope": "individual",
    "iso6393": "gla",
    "iso6392B": "gla",
    "iso6392T": "gla",
    "iso6391": "gd"
  },
  {
    "name": "Irish",
    "type": "living",
    "scope": "individual",
    "iso6393": "gle",
    "iso6392B": "gle",
    "iso6392T": "gle",
    "iso6391": "ga"
  },
  {
    "name": "Galician",
    "type": "living",
    "scope": "individual",
    "iso6393": "glg",
    "iso6392B": "glg",
    "iso6392T": "glg",
    "iso6391": "gl"
  },
  {
    "name": "Manx",
    "type": "living",
    "scope": "individual",
    "iso6393": "glv",
    "iso6392B": "glv",
    "iso6392T": "glv",
    "iso6391": "gv"
  },
  {
    "name": "Guarani",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "grn",
    "iso6392B": "grn",
    "iso6392T": "grn",
    "iso6391": "gn"
  },
  {
    "name": "Gujarati",
    "type": "living",
    "scope": "individual",
    "iso6393": "guj",
    "iso6392B": "guj",
    "iso6392T": "guj",
    "iso6391": "gu"
  },
  {
    "name": "Haitian",
    "type": "living",
    "scope": "individual",
    "iso6393": "hat",
    "iso6392B": "hat",
    "iso6392T": "hat",
    "iso6391": "ht"
  },
  {
    "name": "Hausa",
    "type": "living",
    "scope": "individual",
    "iso6393": "hau",
    "iso6392B": "hau",
    "iso6392T": "hau",
    "iso6391": "ha"
  },
  {
    "name": "Serbo-Croatian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "hbs",
    "iso6392B": null,
    "iso6392T": null,
    "iso6391": "sh"
  },
  {
    "name": "Hebrew",
    "type": "living",
    "scope": "individual",
    "iso6393": "heb",
    "iso6392B": "heb",
    "iso6392T": "heb",
    "iso6391": "he"
  },
  {
    "name": "Herero",
    "type": "living",
    "scope": "individual",
    "iso6393": "her",
    "iso6392B": "her",
    "iso6392T": "her",
    "iso6391": "hz"
  },
  {
    "name": "Hindi",
    "type": "living",
    "scope": "individual",
    "iso6393": "hin",
    "iso6392B": "hin",
    "iso6392T": "hin",
    "iso6391": "hi"
  },
  {
    "name": "Hiri Motu",
    "type": "living",
    "scope": "individual",
    "iso6393": "hmo",
    "iso6392B": "hmo",
    "iso6392T": "hmo",
    "iso6391": "ho"
  },
  {
    "name": "Croatian",
    "type": "living",
    "scope": "individual",
    "iso6393": "hrv",
    "iso6392B": "hrv",
    "iso6392T": "hrv",
    "iso6391": "hr"
  },
  {
    "name": "Hungarian",
    "type": "living",
    "scope": "individual",
    "iso6393": "hun",
    "iso6392B": "hun",
    "iso6392T": "hun",
    "iso6391": "hu"
  },
  {
    "name": "Armenian",
    "type": "living",
    "scope": "individual",
    "iso6393": "hye",
    "iso6392B": "arm",
    "iso6392T": "hye",
    "iso6391": "hy"
  },
  {
    "name": "Igbo",
    "type": "living",
    "scope": "individual",
    "iso6393": "ibo",
    "iso6392B": "ibo",
    "iso6392T": "ibo",
    "iso6391": "ig"
  },
  {
    "name": "Ido",
    "type": "constructed",
    "scope": "individual",
    "iso6393": "ido",
    "iso6392B": "ido",
    "iso6392T": "ido",
    "iso6391": "io"
  },
  {
    "name": "Sichuan Yi",
    "type": "living",
    "scope": "individual",
    "iso6393": "iii",
    "iso6392B": "iii",
    "iso6392T": "iii",
    "iso6391": "ii"
  },
  {
    "name": "Inuktitut",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "iku",
    "iso6392B": "iku",
    "iso6392T": "iku",
    "iso6391": "iu"
  },
  {
    "name": "Interlingue",
    "type": "constructed",
    "scope": "individual",
    "iso6393": "ile",
    "iso6392B": "ile",
    "iso6392T": "ile",
    "iso6391": "ie"
  },
  {
    "name": "Interlingua (International Auxiliary Language Association)",
    "type": "constructed",
    "scope": "individual",
    "iso6393": "ina",
    "iso6392B": "ina",
    "iso6392T": "ina",
    "iso6391": "ia"
  },
  {
    "name": "Indonesian",
    "type": "living",
    "scope": "individual",
    "iso6393": "ind",
    "iso6392B": "ind",
    "iso6392T": "ind",
    "iso6391": "id"
  },
  {
    "name": "Inupiaq",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "ipk",
    "iso6392B": "ipk",
    "iso6392T": "ipk",
    "iso6391": "ik"
  },
  {
    "name": "Icelandic",
    "type": "living",
    "scope": "individual",
    "iso6393": "isl",
    "iso6392B": "ice",
    "iso6392T": "isl",
    "iso6391": "is"
  },
  {
    "name": "Italian",
    "type": "living",
    "scope": "individual",
    "iso6393": "ita",
    "iso6392B": "ita",
    "iso6392T": "ita",
    "iso6391": "it"
  },
  {
    "name": "Javanese",
    "type": "living",
    "scope": "individual",
    "iso6393": "jav",
    "iso6392B": "jav",
    "iso6392T": "jav",
    "iso6391": "jv"
  },
  {
    "name": "Japanese",
    "type": "living",
    "scope": "individual",
    "iso6393": "jpn",
    "iso6392B": "jpn",
    "iso6392T": "jpn",
    "iso6391": "ja"
  },
  {
    "name": "Kalaallisut",
    "type": "living",
    "scope": "individual",
    "iso6393": "kal",
    "iso6392B": "kal",
    "iso6392T": "kal",
    "iso6391": "kl"
  },
  {
    "name": "Kannada",
    "type": "living",
    "scope": "individual",
    "iso6393": "kan",
    "iso6392B": "kan",
    "iso6392T": "kan",
    "iso6391": "kn"
  },
  {
    "name": "Kashmiri",
    "type": "living",
    "scope": "individual",
    "iso6393": "kas",
    "iso6392B": "kas",
    "iso6392T": "kas",
    "iso6391": "ks"
  },
  {
    "name": "Georgian",
    "type": "living",
    "scope": "individual",
    "iso6393": "kat",
    "iso6392B": "geo",
    "iso6392T": "kat",
    "iso6391": "ka"
  },
  {
    "name": "Kanuri",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "kau",
    "iso6392B": "kau",
    "iso6392T": "kau",
    "iso6391": "kr"
  },
  {
    "name": "Kazakh",
    "type": "living",
    "scope": "individual",
    "iso6393": "kaz",
    "iso6392B": "kaz",
    "iso6392T": "kaz",
    "iso6391": "kk"
  },
  {
    "name": "Khmer",
    "type": "living",
    "scope": "individual",
    "iso6393": "khm",
    "iso6392B": "khm",
    "iso6392T": "khm",
    "iso6391": "km"
  },
  {
    "name": "Kikuyu",
    "type": "living",
    "scope": "individual",
    "iso6393": "kik",
    "iso6392B": "kik",
    "iso6392T": "kik",
    "iso6391": "ki"
  },
  {
    "name": "Kinyarwanda",
    "type": "living",
    "scope": "individual",
    "iso6393": "kin",
    "iso6392B": "kin",
    "iso6392T": "kin",
    "iso6391": "rw"
  },
  {
    "name": "Kirghiz",
    "type": "living",
    "scope": "individual",
    "iso6393": "kir",
    "iso6392B": "kir",
    "iso6392T": "kir",
    "iso6391": "ky"
  },
  {
    "name": "Komi",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "kom",
    "iso6392B": "kom",
    "iso6392T": "kom",
    "iso6391": "kv"
  },
  {
    "name": "Kongo",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "kon",
    "iso6392B": "kon",
    "iso6392T": "kon",
    "iso6391": "kg"
  },
  {
    "name": "Korean",
    "type": "living",
    "scope": "individual",
    "iso6393": "kor",
    "iso6392B": "kor",
    "iso6392T": "kor",
    "iso6391": "ko"
  },
  {
    "name": "Kuanyama",
    "type": "living",
    "scope": "individual",
    "iso6393": "kua",
    "iso6392B": "kua",
    "iso6392T": "kua",
    "iso6391": "kj"
  },
  {
    "name": "Kurdish",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "kur",
    "iso6392B": "kur",
    "iso6392T": "kur",
    "iso6391": "ku"
  },
  {
    "name": "Lao",
    "type": "living",
    "scope": "individual",
    "iso6393": "lao",
    "iso6392B": "lao",
    "iso6392T": "lao",
    "iso6391": "lo"
  },
  {
    "name": "Latin",
    "type": "ancient",
    "scope": "individual",
    "iso6393": "lat",
    "iso6392B": "lat",
    "iso6392T": "lat",
    "iso6391": "la"
  },
  {
    "name": "Latvian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "lav",
    "iso6392B": "lav",
    "iso6392T": "lav",
    "iso6391": "lv"
  },
  {
    "name": "Limburgan",
    "type": "living",
    "scope": "individual",
    "iso6393": "lim",
    "iso6392B": "lim",
    "iso6392T": "lim",
    "iso6391": "li"
  },
  {
    "name": "Lingala",
    "type": "living",
    "scope": "individual",
    "iso6393": "lin",
    "iso6392B": "lin",
    "iso6392T": "lin",
    "iso6391": "ln"
  },
  {
    "name": "Lithuanian",
    "type": "living",
    "scope": "individual",
    "iso6393": "lit",
    "iso6392B": "lit",
    "iso6392T": "lit",
    "iso6391": "lt"
  },
  {
    "name": "Luxembourgish",
    "type": "living",
    "scope": "individual",
    "iso6393": "ltz",
    "iso6392B": "ltz",
    "iso6392T": "ltz",
    "iso6391": "lb"
  },
  {
    "name": "Luba-Katanga",
    "type": "living",
    "scope": "individual",
    "iso6393": "lub",
    "iso6392B": "lub",
    "iso6392T": "lub",
    "iso6391": "lu"
  },
  {
    "name": "Ganda",
    "type": "living",
    "scope": "individual",
    "iso6393": "lug",
    "iso6392B": "lug",
    "iso6392T": "lug",
    "iso6391": "lg"
  },
  {
    "name": "Marshallese",
    "type": "living",
    "scope": "individual",
    "iso6393": "mah",
    "iso6392B": "mah",
    "iso6392T": "mah",
    "iso6391": "mh"
  },
  {
    "name": "Malayalam",
    "type": "living",
    "scope": "individual",
    "iso6393": "mal",
    "iso6392B": "mal",
    "iso6392T": "mal",
    "iso6391": "ml"
  },
  {
    "name": "Marathi",
    "type": "living",
    "scope": "individual",
    "iso6393": "mar",
    "iso6392B": "mar",
    "iso6392T": "mar",
    "iso6391": "mr"
  },
  {
    "name": "Macedonian",
    "type": "living",
    "scope": "individual",
    "iso6393": "mkd",
    "iso6392B": "mac",
    "iso6392T": "mkd",
    "iso6391": "mk"
  },
  {
    "name": "Malagasy",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "mlg",
    "iso6392B": "mlg",
    "iso6392T": "mlg",
    "iso6391": "mg"
  },
  {
    "name": "Maltese",
    "type": "living",
    "scope": "individual",
    "iso6393": "mlt",
    "iso6392B": "mlt",
    "iso6392T": "mlt",
    "iso6391": "mt"
  },
  {
    "name": "Mongolian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "mon",
    "iso6392B": "mon",
    "iso6392T": "mon",
    "iso6391": "mn"
  },
  {
    "name": "Maori",
    "type": "living",
    "scope": "individual",
    "iso6393": "mri",
    "iso6392B": "mao",
    "iso6392T": "mri",
    "iso6391": "mi"
  },
  {
    "name": "Malay (macrolanguage)",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "msa",
    "iso6392B": "may",
    "iso6392T": "msa",
    "iso6391": "ms"
  },
  {
    "name": "Burmese",
    "type": "living",
    "scope": "individual",
    "iso6393": "mya",
    "iso6392B": "bur",
    "iso6392T": "mya",
    "iso6391": "my"
  },
  {
    "name": "Nauru",
    "type": "living",
    "scope": "individual",
    "iso6393": "nau",
    "iso6392B": "nau",
    "iso6392T": "nau",
    "iso6391": "na"
  },
  {
    "name": "Navajo",
    "type": "living",
    "scope": "individual",
    "iso6393": "nav",
    "iso6392B": "nav",
    "iso6392T": "nav",
    "iso6391": "nv"
  },
  {
    "name": "South Ndebele",
    "type": "living",
    "scope": "individual",
    "iso6393": "nbl",
    "iso6392B": "nbl",
    "iso6392T": "nbl",
    "iso6391": "nr"
  },
  {
    "name": "North Ndebele",
    "type": "living",
    "scope": "individual",
    "iso6393": "nde",
    "iso6392B": "nde",
    "iso6392T": "nde",
    "iso6391": "nd"
  },
  {
    "name": "Ndonga",
    "type": "living",
    "scope": "individual",
    "iso6393": "ndo",
    "iso6392B": "ndo",
    "iso6392T": "ndo",
    "iso6391": "ng"
  },
  {
    "name": "Nepali (macrolanguage)",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "nep",
    "iso6392B": "nep",
    "iso6392T": "nep",
    "iso6391": "ne"
  },
  {
    "name": "Dutch",
    "type": "living",
    "scope": "individual",
    "iso6393": "nld",
    "iso6392B": "dut",
    "iso6392T": "nld",
    "iso6391": "nl"
  },
  {
    "name": "Norwegian Nynorsk",
    "type": "living",
    "scope": "individual",
    "iso6393": "nno",
    "iso6392B": "nno",
    "iso6392T": "nno",
    "iso6391": "nn"
  },
  {
    "name": "Norwegian Bokmål",
    "type": "living",
    "scope": "individual",
    "iso6393": "nob",
    "iso6392B": "nob",
    "iso6392T": "nob",
    "iso6391": "nb"
  },
  {
    "name": "Norwegian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "nor",
    "iso6392B": "nor",
    "iso6392T": "nor",
    "iso6391": "no"
  },
  {
    "name": "Nyanja",
    "type": "living",
    "scope": "individual",
    "iso6393": "nya",
    "iso6392B": "nya",
    "iso6392T": "nya",
    "iso6391": "ny"
  },
  {
    "name": "Occitan (post 1500)",
    "type": "living",
    "scope": "individual",
    "iso6393": "oci",
    "iso6392B": "oci",
    "iso6392T": "oci",
    "iso6391": "oc"
  },
  {
    "name": "Ojibwa",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "oji",
    "iso6392B": "oji",
    "iso6392T": "oji",
    "iso6391": "oj"
  },
  {
    "name": "Oriya (macrolanguage)",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "ori",
    "iso6392B": "ori",
    "iso6392T": "ori",
    "iso6391": "or"
  },
  {
    "name": "Oromo",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "orm",
    "iso6392B": "orm",
    "iso6392T": "orm",
    "iso6391": "om"
  },
  {
    "name": "Ossetian",
    "type": "living",
    "scope": "individual",
    "iso6393": "oss",
    "iso6392B": "oss",
    "iso6392T": "oss",
    "iso6391": "os"
  },
  {
    "name": "Panjabi",
    "type": "living",
    "scope": "individual",
    "iso6393": "pan",
    "iso6392B": "pan",
    "iso6392T": "pan",
    "iso6391": "pa"
  },
  {
    "name": "Pali",
    "type": "ancient",
    "scope": "individual",
    "iso6393": "pli",
    "iso6392B": "pli",
    "iso6392T": "pli",
    "iso6391": "pi"
  },
  {
    "name": "Polish",
    "type": "living",
    "scope": "individual",
    "iso6393": "pol",
    "iso6392B": "pol",
    "iso6392T": "pol",
    "iso6391": "pl"
  },
  {
    "name": "Portuguese",
    "type": "living",
    "scope": "individual",
    "iso6393": "por",
    "iso6392B": "por",
    "iso6392T": "por",
    "iso6391": "pt"
  },
  {
    "name": "Pushto",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "pus",
    "iso6392B": "pus",
    "iso6392T": "pus",
    "iso6391": "ps"
  },
  {
    "name": "Quechua",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "que",
    "iso6392B": "que",
    "iso6392T": "que",
    "iso6391": "qu"
  },
  {
    "name": "Romansh",
    "type": "living",
    "scope": "individual",
    "iso6393": "roh",
    "iso6392B": "roh",
    "iso6392T": "roh",
    "iso6391": "rm"
  },
  {
    "name": "Romanian",
    "type": "living",
    "scope": "individual",
    "iso6393": "ron",
    "iso6392B": "rum",
    "iso6392T": "ron",
    "iso6391": "ro"
  },
  {
    "name": "Rundi",
    "type": "living",
    "scope": "individual",
    "iso6393": "run",
    "iso6392B": "run",
    "iso6392T": "run",
    "iso6391": "rn"
  },
  {
    "name": "Russian",
    "type": "living",
    "scope": "individual",
    "iso6393": "rus",
    "iso6392B": "rus",
    "iso6392T": "rus",
    "iso6391": "ru"
  },
  {
    "name": "Sango",
    "type": "living",
    "scope": "individual",
    "iso6393": "sag",
    "iso6392B": "sag",
    "iso6392T": "sag",
    "iso6391": "sg"
  },
  {
    "name": "Sanskrit",
    "type": "ancient",
    "scope": "individual",
    "iso6393": "san",
    "iso6392B": "san",
    "iso6392T": "san",
    "iso6391": "sa"
  },
  {
    "name": "Sinhala",
    "type": "living",
    "scope": "individual",
    "iso6393": "sin",
    "iso6392B": "sin",
    "iso6392T": "sin",
    "iso6391": "si"
  },
  {
    "name": "Slovak",
    "type": "living",
    "scope": "individual",
    "iso6393": "slk",
    "iso6392B": "slo",
    "iso6392T": "slk",
    "iso6391": "sk"
  },
  {
    "name": "Slovenian",
    "type": "living",
    "scope": "individual",
    "iso6393": "slv",
    "iso6392B": "slv",
    "iso6392T": "slv",
    "iso6391": "sl"
  },
  {
    "name": "Northern Sami",
    "type": "living",
    "scope": "individual",
    "iso6393": "sme",
    "iso6392B": "sme",
    "iso6392T": "sme",
    "iso6391": "se"
  },
  {
    "name": "Samoan",
    "type": "living",
    "scope": "individual",
    "iso6393": "smo",
    "iso6392B": "smo",
    "iso6392T": "smo",
    "iso6391": "sm"
  },
  {
    "name": "Shona",
    "type": "living",
    "scope": "individual",
    "iso6393": "sna",
    "iso6392B": "sna",
    "iso6392T": "sna",
    "iso6391": "sn"
  },
  {
    "name": "Sindhi",
    "type": "living",
    "scope": "individual",
    "iso6393": "snd",
    "iso6392B": "snd",
    "iso6392T": "snd",
    "iso6391": "sd"
  },
  {
    "name": "Somali",
    "type": "living",
    "scope": "individual",
    "iso6393": "som",
    "iso6392B": "som",
    "iso6392T": "som",
    "iso6391": "so"
  },
  {
    "name": "Southern Sotho",
    "type": "living",
    "scope": "individual",
    "iso6393": "sot",
    "iso6392B": "sot",
    "iso6392T": "sot",
    "iso6391": "st"
  },
  {
    "name": "Spanish",
    "type": "living",
    "scope": "individual",
    "iso6393": "spa",
    "iso6392B": "spa",
    "iso6392T": "spa",
    "iso6391": "es"
  },
  {
    "name": "Albanian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "sqi",
    "iso6392B": "alb",
    "iso6392T": "sqi",
    "iso6391": "sq"
  },
  {
    "name": "Sardinian",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "srd",
    "iso6392B": "srd",
    "iso6392T": "srd",
    "iso6391": "sc"
  },
  {
    "name": "Serbian",
    "type": "living",
    "scope": "individual",
    "iso6393": "srp",
    "iso6392B": "srp",
    "iso6392T": "srp",
    "iso6391": "sr"
  },
  {
    "name": "Swati",
    "type": "living",
    "scope": "individual",
    "iso6393": "ssw",
    "iso6392B": "ssw",
    "iso6392T": "ssw",
    "iso6391": "ss"
  },
  {
    "name": "Sundanese",
    "type": "living",
    "scope": "individual",
    "iso6393": "sun",
    "iso6392B": "sun",
    "iso6392T": "sun",
    "iso6391": "su"
  },
  {
    "name": "Swahili (macrolanguage)",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "swa",
    "iso6392B": "swa",
    "iso6392T": "swa",
    "iso6391": "sw"
  },
  {
    "name": "Swedish",
    "type": "living",
    "scope": "individual",
    "iso6393": "swe",
    "iso6392B": "swe",
    "iso6392T": "swe",
    "iso6391": "sv"
  },
  {
    "name": "Tahitian",
    "type": "living",
    "scope": "individual",
    "iso6393": "tah",
    "iso6392B": "tah",
    "iso6392T": "tah",
    "iso6391": "ty"
  },
  {
    "name": "Tamil",
    "type": "living",
    "scope": "individual",
    "iso6393": "tam",
    "iso6392B": "tam",
    "iso6392T": "tam",
    "iso6391": "ta"
  },
  {
    "name": "Tatar",
    "type": "living",
    "scope": "individual",
    "iso6393": "tat",
    "iso6392B": "tat",
    "iso6392T": "tat",
    "iso6391": "tt"
  },
  {
    "name": "Telugu",
    "type": "living",
    "scope": "individual",
    "iso6393": "tel",
    "iso6392B": "tel",
    "iso6392T": "tel",
    "iso6391": "te"
  },
  {
    "name": "Tajik",
    "type": "living",
    "scope": "individual",
    "iso6393": "tgk",
    "iso6392B": "tgk",
    "iso6392T": "tgk",
    "iso6391": "tg"
  },
  {
    "name": "Tagalog",
    "type": "living",
    "scope": "individual",
    "iso6393": "tgl",
    "iso6392B": "tgl",
    "iso6392T": "tgl",
    "iso6391": "tl"
  },
  {
    "name": "Thai",
    "type": "living",
    "scope": "individual",
    "iso6393": "tha",
    "iso6392B": "tha",
    "iso6392T": "tha",
    "iso6391": "th"
  },
  {
    "name": "Tigrinya",
    "type": "living",
    "scope": "individual",
    "iso6393": "tir",
    "iso6392B": "tir",
    "iso6392T": "tir",
    "iso6391": "ti"
  },
  {
    "name": "Tonga (Tonga Islands)",
    "type": "living",
    "scope": "individual",
    "iso6393": "ton",
    "iso6392B": "ton",
    "iso6392T": "ton",
    "iso6391": "to"
  },
  {
    "name": "Tswana",
    "type": "living",
    "scope": "individual",
    "iso6393": "tsn",
    "iso6392B": "tsn",
    "iso6392T": "tsn",
    "iso6391": "tn"
  },
  {
    "name": "Tsonga",
    "type": "living",
    "scope": "individual",
    "iso6393": "tso",
    "iso6392B": "tso",
    "iso6392T": "tso",
    "iso6391": "ts"
  },
  {
    "name": "Turkmen",
    "type": "living",
    "scope": "individual",
    "iso6393": "tuk",
    "iso6392B": "tuk",
    "iso6392T": "tuk",
    "iso6391": "tk"
  },
  {
    "name": "Turkish",
    "type": "living",
    "scope": "individual",
    "iso6393": "tur",
    "iso6392B": "tur",
    "iso6392T": "tur",
    "iso6391": "tr"
  },
  {
    "name": "Twi",
    "type": "living",
    "scope": "individual",
    "iso6393": "twi",
    "iso6392B": "twi",
    "iso6392T": "twi",
    "iso6391": "tw"
  },
  {
    "name": "Uighur",
    "type": "living",
    "scope": "individual",
    "iso6393": "uig",
    "iso6392B": "uig",
    "iso6392T": "uig",
    "iso6391": "ug"
  },
  {
    "name": "Ukrainian",
    "type": "living",
    "scope": "individual",
    "iso6393": "ukr",
    "iso6392B": "ukr",
    "iso6392T": "ukr",
    "iso6391": "uk"
  },
  {
    "name": "Urdu",
    "type": "living",
    "scope": "individual",
    "iso6393": "urd",
    "iso6392B": "urd",
    "iso6392T": "urd",
    "iso6391": "ur"
  },
  {
    "name": "Uzbek",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "uzb",
    "iso6392B": "uzb",
    "iso6392T": "uzb",
    "iso6391": "uz"
  },
  {
    "name": "Venda",
    "type": "living",
    "scope": "individual",
    "iso6393": "ven",
    "iso6392B": "ven",
    "iso6392T": "ven",
    "iso6391": "ve"
  },
  {
    "name": "Vietnamese",
    "type": "living",
    "scope": "individual",
    "iso6393": "vie",
    "iso6392B": "vie",
    "iso6392T": "vie",
    "iso6391": "vi"
  },
  {
    "name": "Volapük",
    "type": "constructed",
    "scope": "individual",
    "iso6393": "vol",
    "iso6392B": "vol",
    "iso6392T": "vol",
    "iso6391": "vo"
  },
  {
    "name": "Walloon",
    "type": "living",
    "scope": "individual",
    "iso6393": "wln",
    "iso6392B": "wln",
    "iso6392T": "wln",
    "iso6391": "wa"
  },
  {
    "name": "Wolof",
    "type": "living",
    "scope": "individual",
    "iso6393": "wol",
    "iso6392B": "wol",
    "iso6392T": "wol",
    "iso6391": "wo"
  },
  {
    "name": "Xhosa",
    "type": "living",
    "scope": "individual",
    "iso6393": "xho",
    "iso6392B": "xho",
    "iso6392T": "xho",
    "iso6391": "xh"
  },
  {
    "name": "Yiddish",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "yid",
    "iso6392B": "yid",
    "iso6392T": "yid",
    "iso6391": "yi"
  },
  {
    "name": "Yoruba",
    "type": "living",
    "scope": "individual",
    "iso6393": "yor",
    "iso6392B": "yor",
    "iso6392T": "yor",
    "iso6391": "yo"
  },
  {
    "name": "Zhuang",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "zha",
    "iso6392B": "zha",
    "iso6392T": "zha",
    "iso6391": "za"
  },
  {
    "name": "Chinese",
    "type": "living",
    "scope": "macrolanguage",
    "iso6393": "zho",
    "iso6392B": "chi",
    "iso6392T": "zho",
    "iso6391": "zh"
  },
  {
    "name": "Zulu",
    "type": "living",
    "scope": "individual",
    "iso6393": "zul",
    "iso6392B": "zul",
    "iso6392T": "zul",
    "iso6391": "zu"
  }
]
export default languageTable;
